using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Welcome.Model;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace DataLayer.Model
{
    public class DatabaseUser : User
    {
        [Key] //key for the database
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //The value of the field will be autogenerated
        public override int Id {  get; set; }
        // I'm gettig an error 'DatabaseUser.Id': cannot override inherited member 'User.Id'
        // because it is not marked virtual, abstract, or override => to fix that i add keyword
        // "virtual" to the Id method of user.cs file.

    }
}
